INSERT INTO accounts (code, name, account_type, normal_balance, description) VALUES
('scheme_clearing_settlement', 'Scheme Clearing & Settlement Control', 'CONTROL', 'DEBIT',
 'SDCA — clearing control account between scheme and client entries'),
('scheme_debtor',              'Scheme Debtor',              'ASSET',     'DEBIT',
 'Receivable from scheme after SD file matched'),
('scheme_debtor_holding',      'Scheme Debtor Holding',      'ASSET',     'DEBIT',
 'Unmatched scheme receivable pending SD reconciliation'),
('client',                     'Client (MCR)',                'LIABILITY', 'CREDIT',
 'Merchant/client clearing reconciliation account'),
('revenue',                    'Revenue',                     'REVENUE',   'CREDIT',
 'Gross revenue — fees withheld from client'),
('passthrough_cos',            'Passthrough Cost of Sales',   'EXPENSE',   'DEBIT',
 'COS passed through to client'),
('accrued_cos',                'Accrued Cost of Sales',       'LIABILITY', 'CREDIT',
 'Deferred COS pending scheme reconciliation'),
('non_passthrough_cos',        'Non-Passthrough Cost of Sales','EXPENSE',  'DEBIT',
 'COS absorbed by CKO entity'),
('input_tax',                  'Input Tax',                   'LIABILITY', 'CREDIT',
 'VAT / input tax on fees'),
('rolling_reserve',            'Rolling Reserve',             'LIABILITY', 'CREDIT',
 'Reserve withheld from client settlement'),
('expected_client_settlement', 'Expected Client Settlement',  'LIABILITY', 'CREDIT',
 'Pending settlement payable to client'),
('cash',                       'Cash',                        'ASSET',     'DEBIT',
 'Bank cash account'),
('scheme_fee_debtor',          'Scheme Fee Debtor',           'ASSET',     'DEBIT',
 'Variance — scheme fees higher than predicted'),
('scheme_fee_creditor',        'Scheme Fee Creditor',         'LIABILITY', 'CREDIT',
 'Variance — scheme fees lower than predicted'),
('intercompany_debtor_malpb',  'Intercompany Debtor (MALPB)', 'ASSET',     'DEBIT',
 'Intercompany receivable from MALPB entity'),
('intercompany_creditor_malpb','Intercompany Creditor (MALPB)','LIABILITY','CREDIT',
 'Intercompany payable to MALPB entity');
